services:
  db:
    image: mysql:8.0
    container_name: smarttask-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smarttask_db
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - smarttask-net

  backend:
    image: bammite/smarttask-backend:v1
    container_name: smarttask-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: smartuser
      DB_PASSWORD: smartpassword
      DB_NAME: smarttask_db
    depends_on:
      - db
    networks:
      - smarttask-net

  frontend:
    image: bammite/smarttask-frontend:v1
    container_name: smarttask-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - smarttask-net

networks:
  smarttask-net:
    driver: bridge

volumes:
  db_data:
